name: CI

on: [push, pull_request]

env:
  DATABASE_URL: "https://fake.com"
  AWS_REGION: "fake"
  AWS_ID: "fake"
  AWS_SECRET: "fake"
  DATABASE_HOST: "fake"
  DATABASE_PORT: "fake"
  DATABASE_NAME: "fake"
  DATABASE_USERNAME: "fake"
  DATABASE_PASSWORD: "fake"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use PNPM
        uses: pnpm/action-setup@v2.2.4

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install deps (with cache)
        run: pnpm install

      - name: Typecheck
        run: pnpm typecheck

      - name: Lint
        run: pnpm lint

      - name: Test
        run: pnpm test
